version: '3.5'
services:
  opencart:
    build: .
    image: extremepc:latest
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPWD}
      APPHOST: ${APPHOST}
    volumes:
      - ${SITEDIR}:/var/www/html
      - ${STORAGEDIR}:/var/www/storage
#      - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/config.php:/var/www/html/config.php
      - ./config/config_admin.php:/var/www/html/admin/config.php
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8183:80
    links:
      - db
    networks:
      - extremepc_net
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPWD}
      MYSQL_DATABASE: roctech
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - extremepc_net
  dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPWD}
    ports:
      - 8080:80
    networks:
      - extremepc_net
  italker:
    build:
      context: .
      dockerfile: Dockerfile_italker
    image: italker:latest
    restart: always
    command: /bin/bash start.sh
    volumes:
      - ./config/start.sh:/var/www/start.sh
      - ${ITALKERDIR}:/var/www
      - ${SITEDIR}/image:/image
    environment:
      EXTREMEPC_PASSWORD: ${DBPWD}
    ports:
      - 8184:8080
    networks:
      - extremepc_net
    links:
      - db
networks:
  extremepc_net:
volumes:
  mysql-data:


