version: '3.5'
services:
  opencart:
    build: .
    image: extremepc:latest
    deploy:
      resources:
        limits:
          cpus: '0.90'
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_USER: ${DBUSER}
      MYSQL_HOST: ${DBHOST}
      MYSQL_PASSWORD: ${DBPWD}
      APPHOST: ${APPHOST}
    volumes:
      - ${SITEDIR}:/var/www/html
      - ${STORAGEDIR}:/var/www/storage
#      - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/config.php:/var/www/html/config.php
      - ./config/config_admin.php:/var/www/html/admin/config.php
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8180-8181:80
    links:
      - db
    networks:
      - extremepc_net
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPWD}
      MYSQL_DATABASE: roctech
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    networks:
      - extremepc_net
  redis:
    image: redis
    restart: always
    networks:
      - extremepc_net
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPWD}
#      PMA_HOST: ${DBHOST}
    ports:
      - 8081:80
    networks:
      - extremepc_net
  italker:
    build:
      context: .
      dockerfile: Dockerfile_italker
    image: italker:latest
    restart: always
    command: /bin/bash start.sh
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./config/start.sh:/var/www/start.sh
      - ${ITALKERDIR}:/var/www
      - ${SITEDIR}/image:/image
    environment:
      EXTREMEPC_USER: ${DBUSER}
      EXTREMEPC_HOST: ${DBHOST}
      EXTREMEPC_PASSWORD: ${DBPWD}
      ROCTECH_REMOTE: ${ROCTECH_REMOTE}
      APP_KEY: ${APP_KEY}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
    ports:
      - 8184:8080
    networks:
      - extremepc_net
    links:
      - db
      - redis
  worker:
    depends_on:
      - italker
    image: italker:latest
    restart: always
    volumes:
      - ./config/worker.sh:/var/www/start.sh
      - ${ITALKERDIR}:/var/www
      - ${SITEDIR}/image:/image
    environment:
      EXTREMEPC_USER: ${DBUSER}
      EXTREMEPC_HOST: ${DBHOST}
      EXTREMEPC_PASSWORD: ${DBPWD}
      ROCTECH_REMOTE: ${ROCTECH_REMOTE}
      APP_KEY: ${APP_KEY}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
    networks:
      - extremepc_net
    links:
      - db
      - redis
    command: /bin/bash start.sh

networks:
  extremepc_net:
volumes:
  mysql-data:


